name: Update Metrics

on:
  schedule:
    # Runs at 10:15 every day
    - cron: '20 8 * * *'
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Generate and save metrics
      env:
        PD_TOKEN: ${{ secrets.PD_TOKEN }}
      run: ruby lib/capture_log_entries.rb

    - name: Commit and push if changed
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/apoorva-babbel/literate-chainsaw.git
        git add lib/team_metrics.json
        git commit -m "Added new metrics" #|| exit 0   # This will exit with 0 if there's nothing to commit
        git push origin main
