name: Update Schedule

on:
  schedule:
    # Runs every 12th of the month at 11:15
    - cron: '15 11 12 * *'
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Generate and save schedule
      run: ruby generate_schedule.rb

    - name: Commit and push if changed
      run: |
        git config --global user.email "ajain@babbel.com"
        git config --global user.name "Apoorva"
        git add lib
        git commit -m "Test update" || exit 0   # This will exit with 0 if there's nothing to commit
        git push
