name: Update Schedule

on:
  schedule:
    # Runs at 05:00 every Monday
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Check secret is loaded
      run: |
        if [ -z "${{ secrets.PD_TOKEN }}" ]; then
          echo "Secret is empty or not loaded!"
          exit 1
        else
          echo "Secret is loaded!"
        fi

    - name: Generate and save schedule
      env:
        PD_TOKEN: ${{ secrets.PD_TOKEN }}
      run: ruby lib/generate_schedule.rb

    - name: Commit and push if changed
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/apoorva-babbel/literate-chainsaw.git
        git add .
        git commit -m "Test update" #|| exit 0   # This will exit with 0 if there's nothing to commit
        git push origin main
